-- =============================
-- SCHEMA
-- =============================
DROP SCHEMA IF EXISTS DB_SA CASCADE;
CREATE SCHEMA DB_SA;
SET SCHEMA DB_SA;

-- =============================
-- DROP TABLES
-- =============================
DROP TABLE IF EXISTS T_CUPOM_CLIENTE;
DROP TABLE IF EXISTS T_ITEM_PEDIDO;
DROP TABLE IF EXISTS T_PRODUTO_COMBO;
DROP TABLE IF EXISTS T_SGP_PRODUTO;
DROP TABLE IF EXISTS T_SGP_PEDIDO;
DROP TABLE IF EXISTS T_SGP_CUPOM;
DROP TABLE IF EXISTS T_SGP_COMBO;
DROP TABLE IF EXISTS T_SGP_MIDIA;
DROP TABLE IF EXISTS T_SGP_ITEM;
DROP TABLE IF EXISTS T_SGP_FUNCIONARIO;
DROP TABLE IF EXISTS T_SGP_GERENTE;
DROP TABLE IF EXISTS T_SGP_CLIENTE;
DROP TABLE IF EXISTS T_SGP_PARCEIRO;
DROP TABLE IF EXISTS T_SGP_FORMA_PAGAMENTO;
DROP TABLE IF EXISTS T_SGP_CATEGORIA_PRODUTO;

-- =============================
-- CREATE TABLES (nomes corrigidos)
-- =============================

CREATE TABLE T_SGP_CATEGORIA_PRODUTO (
    id_categoria INT NOT NULL,
    nm_categoria VARCHAR(50) NOT NULL,
    sg_categoria CHAR(2) NOT NULL,
    sq_imagem BLOB NOT NULL
);

CREATE TABLE T_SGP_CLIENTE (
    id_cliente INT NOT NULL,
    nm_cliente VARCHAR(150) NOT NULL,
    nr_telefone CHAR(11),
    nr_cpf CHAR(14) NOT NULL,
    dt_registro TIMESTAMP NOT NULL
);

CREATE TABLE T_SGP_ITEM (
    id_item INT NOT NULL,
    nm_item VARCHAR(150) NOT NULL,
    ds_item VARCHAR(255) NOT NULL,
    tp_item CHAR(1) NOT NULL,
    dt_criacao TIMESTAMP NOT NULL,
    st_ativo TINYINT NOT NULL
);

CREATE TABLE T_SGP_PARCEIRO (
    id_parceiro INT NOT NULL,
    nm_parceiro VARCHAR(150) NOT NULL,
    ds_email VARCHAR(100) NOT NULL,
    nr_telefone CHAR(11) NOT NULL
);

CREATE TABLE T_SGP_FORMA_PAGAMENTO (
    id_pagamento INT NOT NULL,
    nm_pagamento VARCHAR(30) NOT NULL,
    sg_pagamento CHAR(3) NOT NULL,
    sq_imagem BLOB NOT NULL
);

CREATE TABLE T_SGP_FUNCIONARIO (
    id_funcionario INT NOT NULL,
    id_gerente INT,
    nm_funcionario VARCHAR(150) NOT NULL,
    dt_nascimento DATE NOT NULL,
    nr_cpf CHAR(14) NOT NULL
);

CREATE TABLE T_SGP_GERENTE (
    id_funcionario INT NOT NULL,
    ds_senha CHAR(255) NOT NULL,
    nm_login VARCHAR(150) NOT NULL
);

CREATE TABLE T_SGP_CUPOM (
    id_cupom INT NOT NULL,
    id_parceiro INT NOT NULL,
    vl_desconto DECIMAL(6,2) NOT NULL,
    ds_cupom TEXT NOT NULL,
    nm_cupom VARCHAR(10) NOT NULL,
    st_valido TINYINT NOT NULL
);

CREATE TABLE T_SGP_PRODUTO (
    id_item INT NOT NULL,
    id_categoria INT NOT NULL,
    vl_produto DECIMAL(6,2) NOT NULL
);

CREATE TABLE T_SGP_COMBO (
    id_item INT NOT NULL,
    vl_desconto DECIMAL(6,2) NOT NULL
);

CREATE TABLE T_SGP_MIDIA (
    id_midia INT NOT NULL,
    id_item INT NOT NULL,
    ds_midia VARCHAR(255) NOT NULL,
    sq_midia BLOB NOT NULL,
    tp_midia CHAR(1) NOT NULL
);

CREATE TABLE T_SGP_PEDIDO (
    id_pedido INT NOT NULL,
    id_funcionario INT,
    id_pagamento INT NOT NULL,
    id_cliente INT,
    id_cupom INT,
    dt_pedido TIMESTAMP NOT NULL,
    nm_cliente VARCHAR(150),
    st_pedido CHAR(1) NOT NULL
);

CREATE TABLE T_CUPOM_CLIENTE (
    id_cliente INT NOT NULL,
    id_cupom INT NOT NULL
);

CREATE TABLE T_ITEM_PEDIDO (
    id_item INT NOT NULL,
    id_pedido INT NOT NULL,
    nr_quantidade INT NOT NULL
);

CREATE TABLE T_PRODUTO_COMBO (
    id_item_combo INT NOT NULL,
    id_item_produto INT NOT NULL,
    nr_quantidade INT NOT NULL
);

-- =============================
-- PRIMARY KEYS
-- =============================
ALTER TABLE T_SGP_CATEGORIA_PRODUTO
    ALTER COLUMN id_categoria INT AUTO_INCREMENT;
ALTER TABLE T_SGP_CATEGORIA_PRODUTO
    ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (id_categoria);

ALTER TABLE T_SGP_CLIENTE
    ALTER COLUMN id_cliente INT AUTO_INCREMENT;
ALTER TABLE T_SGP_CLIENTE
    ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (id_cliente);

ALTER TABLE T_SGP_ITEM
    ALTER COLUMN id_item INT AUTO_INCREMENT;
ALTER TABLE T_SGP_ITEM
    ADD CONSTRAINT PK_ITEM PRIMARY KEY (id_item);

ALTER TABLE T_SGP_PARCEIRO
    ALTER COLUMN id_parceiro INT AUTO_INCREMENT;
ALTER TABLE T_SGP_PARCEIRO
    ADD CONSTRAINT PK_PARCEIRO PRIMARY KEY (id_parceiro);

ALTER TABLE T_SGP_FORMA_PAGAMENTO
    ALTER COLUMN id_pagamento INT AUTO_INCREMENT;
ALTER TABLE T_SGP_FORMA_PAGAMENTO
    ADD CONSTRAINT PK_PAGAMENTO PRIMARY KEY (id_pagamento);

ALTER TABLE T_SGP_FUNCIONARIO
    ALTER COLUMN id_funcionario INT AUTO_INCREMENT;
ALTER TABLE T_SGP_FUNCIONARIO
    ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (id_funcionario);

ALTER TABLE T_SGP_GERENTE
    ADD CONSTRAINT PK_GERENTE PRIMARY KEY (id_funcionario);

ALTER TABLE T_SGP_CUPOM
    ALTER COLUMN id_cupom INT AUTO_INCREMENT;
ALTER TABLE T_SGP_CUPOM
    ADD CONSTRAINT PK_CUPOM PRIMARY KEY (id_cupom);

ALTER TABLE T_SGP_PRODUTO
    ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (id_item);

ALTER TABLE T_SGP_COMBO
    ADD CONSTRAINT PK_COMBO PRIMARY KEY (id_item);

ALTER TABLE T_SGP_MIDIA
    ALTER COLUMN id_midia INT AUTO_INCREMENT;
ALTER TABLE T_SGP_MIDIA
    ADD CONSTRAINT PK_MIDIA PRIMARY KEY (id_midia);

ALTER TABLE T_SGP_PEDIDO
    ALTER COLUMN id_pedido INT AUTO_INCREMENT;
ALTER TABLE T_SGP_PEDIDO
    ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (id_pedido);

ALTER TABLE T_CUPOM_CLIENTE
    ADD CONSTRAINT PK_CUPOM_CLIENTE PRIMARY KEY (id_cliente, id_cupom);

ALTER TABLE T_ITEM_PEDIDO
    ADD CONSTRAINT PK_ITEM_PEDIDO PRIMARY KEY (id_item, id_pedido);

ALTER TABLE T_PRODUTO_COMBO
    ADD CONSTRAINT PK_PRODUTO_COMBO PRIMARY KEY (id_item_combo, id_item_produto);

-- =============================
-- FOREIGN KEYS
-- =============================
ALTER TABLE T_SGP_FUNCIONARIO
    ADD CONSTRAINT FK_GER_FUNC FOREIGN KEY (id_gerente) REFERENCES T_SGP_FUNCIONARIO(id_funcionario);

ALTER TABLE T_SGP_GERENTE
    ADD CONSTRAINT FK_FUNC_GER FOREIGN KEY (id_funcionario) REFERENCES T_SGP_FUNCIONARIO(id_funcionario);

ALTER TABLE T_SGP_CUPOM
    ADD CONSTRAINT FK_CUPOM_PARCEIRO FOREIGN KEY (id_parceiro) REFERENCES T_SGP_PARCEIRO(id_parceiro);

ALTER TABLE T_SGP_PRODUTO
    ADD CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (id_categoria) REFERENCES T_SGP_CATEGORIA_PRODUTO(id_categoria);

ALTER TABLE T_SGP_PRODUTO
    ADD CONSTRAINT FK_PRODUTO_ITEM FOREIGN KEY (id_item) REFERENCES T_SGP_ITEM(id_item);

ALTER TABLE T_SGP_COMBO
    ADD CONSTRAINT FK_COMBO_ITEM FOREIGN KEY (id_item) REFERENCES T_SGP_ITEM(id_item);

ALTER TABLE T_SGP_MIDIA
    ADD CONSTRAINT FK_MIDIA_ITEM FOREIGN KEY (id_item) REFERENCES T_SGP_ITEM(id_item);

ALTER TABLE T_SGP_PEDIDO
    ADD CONSTRAINT FK_PEDIDO_FUNC FOREIGN KEY (id_funcionario) REFERENCES T_SGP_FUNCIONARIO(id_funcionario);

ALTER TABLE T_SGP_PEDIDO
    ADD CONSTRAINT FK_PEDIDO_PAGAMENTO FOREIGN KEY (id_pagamento) REFERENCES T_SGP_FORMA_PAGAMENTO(id_pagamento);

ALTER TABLE T_SGP_PEDIDO
    ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (id_cliente) REFERENCES T_SGP_CLIENTE(id_cliente);

ALTER TABLE T_SGP_PEDIDO
    ADD CONSTRAINT FK_PEDIDO_CUPOM FOREIGN KEY (id_cupom) REFERENCES T_SGP_CUPOM(id_cupom);

ALTER TABLE T_CUPOM_CLIENTE
    ADD CONSTRAINT FK_CUPOM_CLIENTE FOREIGN KEY (id_cliente) REFERENCES T_SGP_CLIENTE(id_cliente);

ALTER TABLE T_CUPOM_CLIENTE
    ADD CONSTRAINT FK_CLIENTE_CUPOM FOREIGN KEY (id_cupom) REFERENCES T_SGP_CUPOM(id_cupom);

ALTER TABLE T_ITEM_PEDIDO
    ADD CONSTRAINT FK_PEDIDO_ITEM FOREIGN KEY (id_item) REFERENCES T_SGP_ITEM(id_item);

ALTER TABLE T_ITEM_PEDIDO
    ADD CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (id_pedido) REFERENCES T_SGP_PEDIDO(id_pedido);

ALTER TABLE T_PRODUTO_COMBO
    ADD CONSTRAINT FK_PRODUTO_COMBO FOREIGN KEY (id_item_combo) REFERENCES T_SGP_COMBO(id_item);

ALTER TABLE T_PRODUTO_COMBO
    ADD CONSTRAINT FK_COMBO_PRODUTO FOREIGN KEY (id_item_produto) REFERENCES T_SGP_PRODUTO(id_item);
